//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_Galleries
    {
        [Key]
        public int GalleryID { get; set; }
        [Display(Name = "کالا")]
        public int ProductID { get; set; }
        [Display(Name = "تصویر")]
        public string ImageName { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
